#ifndef FILE_PARSER_CFG_H
#define FILE_PARSER_CFG_H
/*
 * U OVOM FAJLU JE SADRZANA KONFIGURACIJA FAJL PARSERA
*/

// EVENTUALNO OSPOSOBITI PARSER DA SE UNOSE NOVE BOJE, ILI KOMANDE (KOMANDE SU OVERKIL)
//KADA BIH ZNAO NAPRAVITI UNIVERZALNI INTERPRETER NA JEDNOSTAVAN NACIN, SAD BIH BIO MILIONER :P

//Ovaj define oznacava makskimalnu velicinu bafera za cuvanje komandi
#define MAX_NUM_OF_LINES 100
#define MAX_SIZE_OF_LINES 100

#define DYNAMIC_ALLOCATION

#ifndef DYNAMIC_ALLOCATION
    #define MAX_NUM_OF_LINES 100
    #define MAX_SIZE_OF_LINES 100
#endif

#endif